/*
 *    Copyright 2023 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package io.github.sqlx.jdbc;

import io.github.sqlx.sql.parser.AnnotationSqlHintParser;
import io.github.sqlx.sql.parser.SqlHint;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * @author He Xing Mo
 * @since 1.0
 */
public class AnnotationSqlStatement extends StatementAdapter {

    private final AnnotationSqlHintParser parser;

    public AnnotationSqlStatement(Statement delegate , AnnotationSqlHintParser parser) {
        super(delegate);
        this.parser = parser;
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        return super.executeQuery(getNativeSql(sql));
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        return super.executeUpdate(getNativeSql(sql));
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        super.addBatch(getNativeSql(sql));
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return super.executeUpdate(getNativeSql(sql), autoGeneratedKeys);
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return super.executeUpdate(getNativeSql(sql), columnIndexes);
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        return super.executeUpdate(getNativeSql(sql), columnNames);
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        return super.execute(getNativeSql(sql), autoGeneratedKeys);
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return super.execute(getNativeSql(sql), columnIndexes);
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        return super.execute(getNativeSql(sql), columnNames);
    }

    @Override
    public long executeLargeUpdate(String sql) throws SQLException {
        return super.executeLargeUpdate(getNativeSql(sql));
    }

    @Override
    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return super.executeLargeUpdate(getNativeSql(sql), autoGeneratedKeys);
    }

    @Override
    public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return super.executeLargeUpdate(getNativeSql(sql), columnIndexes);
    }

    @Override
    public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
        return super.executeLargeUpdate(getNativeSql(sql), columnNames);
    }

    private String getNativeSql(String sql) {
        SqlHint hint = parser.parse(sql);
        return hint.getNativeSql();
    }
}
